name: CI

on: # This workflow is activated from either push or pull request events.
  push:
    branches: [main, master]
  pull_request: # When a contributor ask the maintainer fo a Git repository to review code to be merged.

jobs:
  build:
    runs-on: ubuntu-latest # Configures the job to run on the latest version of a Ubuntu Linux runner.

    strategy:
      fail-fast: false
      matrix:
        include:
          - board: jetson-nano
            revision: 300

    env:
      JETSON_ROOTFS_DIR: /tmp/jetson-builder/rootfs
      JETSON_BUILD_DIR: /tmp/jetson-builder/build
      JETSON_NANO_BOARD: ${{ matrix.board }}
      JETSON_NANO_REVISION: ${{ matrix.revision }}
    steps: # All these steps are run on the Linux environment of the runner.
      - uses: actions/checkout@v2 # Checks out the repository onto the runner, allows scripts or other actions from the repo to be run in the runner.

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build docker image
        run: docker buildx build --platform linux/arm64 -t jetson-nano-image .

      - name: Export rootfs
        run: |
          docker export $(docker create --name nano-rootfs --platform linux/arm64 jetson-nano-image) -o rootfs.tar
          docker rm nano-rootfs
          mkdir -p /tmp/jetson-builder/rootfs
          sudo tar --same-owner -xf rootfs.tar -C /tmp/jetson-builder/rootfs

      - name: Create jetson.img
        run: |
          sudo apt install -y libxml2-utils
          sudo -E ./create-image.sh

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.board }}-r${{ matrix.revision }}
          path: |
            jetson.img
